name: Deploy my lambda function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out comminity code
        uses: actions/checkout@v2
      - name: Set up code
        uses: actions/setup-python@v2
      - name: Install libraries
        run : |
              cd function
              python -m pip install --upgrade pip
              if [ -f reqrements.txt ]; then pip install -r requirements.txt.; fi
      - name: Create zip bundle
        run: |
             cd function
             zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
      
